### ISSUE TITLE
The command 'Project Boss: Open in new Window' fail every time

### ISSUE THREAD

**Issue by MartinWallgren** [angus-mcritchie/project-boss#1]
The command 'Project Boss: Open in new Window' fails with "Cannot read properties  of undefined (reading 'fullPath')

![image](https://github.com/angus-mcritchie/project-boss/assets/924858/069ecae9-4a9a-427c-87eb-895ff26ba1a5)

I ran the command by from the command menu:
![image](https://github.com/angus-mcritchie/project-boss/assets/924858/7df01f92-7aca-4f82-b20a-e969ec68c3c5)

**About from my VS Code**
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.10.0-26-amd64

**Comment by angus-mcritchie** [comment]
Thanks for reporting this @MartinWallgren. I had some time today and released version 0.1.0, which fixes this issue and more ❤️
