### ISSUE TITLE
restore possibility to "open in same window" by default

### ISSUE THREAD

**Issue by Samba25leo** [angus-mcritchie/project-boss#3]
in v0.0.5 you had the possibility by default to open a project in the actual window and if you wanted it in a new window you had to specify by clicking on the cornered icon or with the command, but since the 0.1.0 it's always a new window. even when not specified. i saw there was a change in how a project is opened.
btw: i'm working on mac

**Comment by angus-mcritchie** [comment]
You're totally right @Samba25leo. It has been bugging me a little bit too, but not enough for me to get on it right away.
I'll fix it soon when I get some free time, in the meantime, PRs are welcomed ❤️

**Comment by angus-mcritchie** [comment]
Actually, @Samba25leo it was an annoyingly easy fix so I just pushed it now. Update the extension in VS Code and it will work now 👍
